source :gemcutter
gem 'rails', '2.3.5'
gem 'warden', '0.9.3'
gem 'devise', '1.0.2'
gem 'haml'
gem 'compass'
gem 'formtastic'
gem 'acts-as-taggable-on'
gem 'validates_timeliness'
gem 'exceptional', :version => '2.0.6'
