source :gemcutter
gem 'rails', '2.3.5'
gem 'warden', '0.9.3'
gem 'devise', '1.0.2'
gem 'haml', '2.2.22'
gem 'compass'
gem 'formtastic'
gem 'acts-as-taggable-on'
gem 'validates_timeliness'
gem 'simple-navigation'
gem 'searchlogic'
